package com.example.testapplication;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DividerItemDecoration;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;

public class AddListActivity extends AppCompatActivity {

    private RecyclerView listsRecyclerView;
    RecyclerView.LayoutManager layoutManager;
    ListsRecyclerViewAdapter listsRecyclerViewAdapter;
    EditText listEditText;
    View addListButton;
    View backButton;

    ArrayList<Category> categories = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_list);

        listsRecyclerView = findViewById(R.id.listsRecyclerView);
        listEditText = findViewById(R.id.listEditText);
        addListButton = findViewById(R.id.addListButton);
        backButton = findViewById(R.id.backButton);

        Intent intent = getIntent();
        categories = intent.getParcelableArrayListExtra(MainActivity.KEY_NAME);

        initRecyclerView();

        listEditText.setOnEditorActionListener(editorActionListener);

        addListButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v)
            {onAddListClick();}
        });

        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {finish();}
        });
    }

    private void initRecyclerView()
    {
        layoutManager = new LinearLayoutManager(this);
        listsRecyclerView.setLayoutManager(layoutManager);
        listsRecyclerViewAdapter = new ListsRecyclerViewAdapter(categories);
        listsRecyclerView.setAdapter(listsRecyclerViewAdapter);
        new ItemTouchHelper(itemTouchHelperCallback).attachToRecyclerView(listsRecyclerView);

        DividerItemDecoration dividerItemDecoration = new DividerItemDecoration(this, DividerItemDecoration.VERTICAL);
        dividerItemDecoration.setDrawable(getResources().getDrawable(R.drawable.divider_line, null));
        listsRecyclerView.addItemDecoration(dividerItemDecoration);

    }

    private TextView.OnEditorActionListener editorActionListener = new TextView.OnEditorActionListener() {
        @Override
        public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
            onAddListClick();

            return true;
        }
    };

    private void onAddListClick()
    {
        final DatabaseReference myRef = FirebaseDatabase.getInstance().getReference("CategoryList");

        final String text = listEditText.getText().toString();

        myRef.orderByValue().equalTo(text).addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if(dataSnapshot.exists())
                {
                    Toast.makeText(AddListActivity.this, "This list already exists", Toast.LENGTH_SHORT).show();
                } else
                    {
                        if (text.trim().length() > 0)
                        {
                            String autoGeneratedId = myRef.push().getKey();

                            categories.add(new Category(text, autoGeneratedId));

                            listsRecyclerViewAdapter.notifyDataSetChanged();

                            listEditText.getText().clear();

                            myRef.child(autoGeneratedId).setValue(text);

                            Toast.makeText(AddListActivity.this, "New list added", Toast.LENGTH_SHORT).show();
                            finish();
                        } else
                        {
                            Toast.makeText(AddListActivity.this, "You did not enter any text", Toast.LENGTH_SHORT).show();
                        }
                    }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });
    }

    ItemTouchHelper.SimpleCallback itemTouchHelperCallback = new ItemTouchHelper.SimpleCallback(0, ItemTouchHelper.LEFT) {
        @Override
        public boolean onMove(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder, @NonNull RecyclerView.ViewHolder target) {
            return false;
        }

        @Override
        public void onSwiped(@NonNull RecyclerView.ViewHolder viewHolder, int direction) {
            final DatabaseReference myRef = FirebaseDatabase.getInstance().getReference("CategoryList");
            DatabaseReference taskListRef = FirebaseDatabase.getInstance().getReference("TaskList");

            String categoryId = categories.get(viewHolder.getAdapterPosition()).getCategoryId();
            String categoryName = categories.get(viewHolder.getAdapterPosition()).getCategoryName();

            if (categories.size() > 1)
            {
                categories.remove(viewHolder.getAdapterPosition());

                myRef.child(categoryId).removeValue();
                taskListRef.child(categoryName).removeValue();
            }
            else
                {
                    Toast.makeText(AddListActivity.this, "You cannot delete last remaining list", Toast.LENGTH_SHORT).show();
                }
            listsRecyclerViewAdapter.notifyDataSetChanged();
        }
    };
}
