package com.example.testapplication;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DividerItemDecoration;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;

public class AddListActivity extends AppCompatActivity {

    private RecyclerView listsRecyclerView;
    RecyclerView.LayoutManager layoutManager;
    ListsRecyclerViewAdapter listsRecyclerViewAdapter;
    EditText listEditText;
    View addListButton;
    View backButton;
    FirebaseAuth mAuth;

    ArrayList<Category> categories = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_list);

        listsRecyclerView = findViewById(R.id.listsRecyclerView);
        listEditText = findViewById(R.id.listEditText);
        addListButton = findViewById(R.id.addListButton);
        backButton = findViewById(R.id.backButton);

        mAuth = FirebaseAuth.getInstance();

        Intent intent = getIntent();
        categories = intent.getParcelableArrayListExtra(MainActivity.KEY_NAME);

        initRecyclerView();

        listEditText.setOnEditorActionListener(editorActionListener);

        addListButton.setOnClickListener(v -> onAddListClick());

        backButton.setOnClickListener(v -> finish());
    }

    private void initRecyclerView()
    {
        layoutManager = new LinearLayoutManager(this);
        listsRecyclerView.setLayoutManager(layoutManager);
        listsRecyclerViewAdapter = new ListsRecyclerViewAdapter(categories);
        listsRecyclerView.setAdapter(listsRecyclerViewAdapter);
        new ItemTouchHelper(itemTouchHelperCallback).attachToRecyclerView(listsRecyclerView);

        DividerItemDecoration dividerItemDecoration = new DividerItemDecoration(this, DividerItemDecoration.VERTICAL);
        dividerItemDecoration.setDrawable(getResources().getDrawable(R.drawable.divider_line, null));
        listsRecyclerView.addItemDecoration(dividerItemDecoration);

    }

    private final TextView.OnEditorActionListener editorActionListener = (v, actionId, event) -> {
        onAddListClick();

        return true;
    };

    private void onAddListClick()
    {
        String userId = mAuth.getCurrentUser().getUid();
        final DatabaseReference categoryDBRef = FirebaseDatabase.getInstance().getReference(userId).child("CategoryList");

        final String text = listEditText.getText().toString();

        categoryDBRef.orderByValue().equalTo(text).addListenerForSingleValueEvent(new ValueEventListener() {

            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if(dataSnapshot.exists())
                {
                    Toast.makeText(AddListActivity.this, "This list already exists", Toast.LENGTH_SHORT).show();
                } else
                    {
                        if (text.trim().length() > 0)
                        {
                            String autoGeneratedId = categoryDBRef.push().getKey();

                            categories.add(new Category(text, autoGeneratedId));

                            listsRecyclerViewAdapter.notifyDataSetChanged();

                            listEditText.getText().clear();

                            categoryDBRef.child(autoGeneratedId).setValue(text);

                            Toast.makeText(AddListActivity.this, "New list added", Toast.LENGTH_SHORT).show();

                            SharedPreferences sharedPrefs = getSharedPreferences(MainActivity.SHARED_PREFS, 0);
                            SharedPreferences.Editor sharedPrefsEditor = sharedPrefs.edit();
                            sharedPrefsEditor.putInt(MainActivity.SPINNER_CHOICE, categories.size() - 1);
                            sharedPrefsEditor.apply();

                            finish();
                        } else
                        {
                            Toast.makeText(AddListActivity.this, "You did not enter any text", Toast.LENGTH_SHORT).show();
                        }
                    }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });
    }

    ItemTouchHelper.SimpleCallback itemTouchHelperCallback = new ItemTouchHelper.SimpleCallback(0, ItemTouchHelper.LEFT) {
        @Override
        public boolean onMove(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder, @NonNull RecyclerView.ViewHolder target) {
            return false;
        }

        @Override
        public void onSwiped(@NonNull RecyclerView.ViewHolder viewHolder, int direction) {
            String userId = mAuth.getCurrentUser().getUid();
            final DatabaseReference categoryDBRef = FirebaseDatabase.getInstance().getReference(userId).child("CategoryList");
            DatabaseReference taskDBRef = FirebaseDatabase.getInstance().getReference(userId).child("TaskList");

            String categoryId = categories.get(viewHolder.getBindingAdapterPosition()).getCategoryId();
            String categoryName = categories.get(viewHolder.getBindingAdapterPosition()).getCategoryName();

            if (categories.size() > 1)
            {
                SharedPreferences sharedPrefs = getSharedPreferences(MainActivity.SHARED_PREFS, 0);
                SharedPreferences.Editor sharedPrefsEditor = sharedPrefs.edit();
                int spinnerChoice = sharedPrefs.getInt(MainActivity.SPINNER_CHOICE, 0);
               
                if (viewHolder.getBindingAdapterPosition() == spinnerChoice)
                {
                    sharedPrefsEditor.putInt(MainActivity.SPINNER_CHOICE, 0);
                    sharedPrefsEditor.apply();
                }

                categories.remove(viewHolder.getBindingAdapterPosition());

                categoryDBRef.child(categoryId).removeValue();
                taskDBRef.child(categoryName).removeValue();
            }
            else
                {
                    Toast.makeText(AddListActivity.this, "You cannot delete last remaining list", Toast.LENGTH_SHORT).show();
                }
            listsRecyclerViewAdapter.notifyDataSetChanged();
        }
    };
}
