package com.example.testapplication;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.recyclerview.widget.DividerItemDecoration;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.graphics.Canvas;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;

import java.util.ArrayList;

import it.xabaras.android.recyclerview.swipedecorator.RecyclerViewSwipeDecorator;

public class TaskItemActivity extends AppCompatActivity {

    private RecyclerView recyclerView;
    RecyclerView.LayoutManager layoutManager;
    SubTasksRecyclerViewAdapter subTasksRecyclerViewAdapter;
    EditText informationEditText;
    EditText subTaskEditText;
    FirebaseAuth mAuth;
    String categoryId;
    String taskId;
    Task superTask;
    private FirebaseHelper firebaseHelper;

    ArrayList<SubTask> list = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_task_item);

        RelativeLayout relativeLayout = findViewById(R.id.relativeLayout);
        recyclerView = findViewById(R.id.recyclerView);
        TextView superTaskTextView = findViewById(R.id.superTaskTextView);
        informationEditText = findViewById(R.id.informationEditText);
        subTaskEditText = findViewById(R.id.subTaskEditText);

        mAuth = FirebaseAuth.getInstance();

        firebaseHelper = new FirebaseHelper();

        Intent intent = getIntent();
        superTask = intent.getParcelableExtra(MainActivity.KEY_NAME);
        categoryId = intent.getStringExtra(MainActivity.KEY_NAME_TWO);
        list.addAll(superTask.getSubTasksList());

        superTaskTextView.setText(superTask.getTaskName());
        informationEditText.setText(superTask.getTaskInformation());
        taskId = superTask.getTaskId();

        initRecyclerView();

        relativeLayout.setOnClickListener(v -> finish());

        subTaskEditText.setOnEditorActionListener(editorActionListener);
        informationEditText.setOnEditorActionListener(editorActionListener);
        informationEditText.setOnFocusChangeListener(onFocusChangeListener);
    }

    private void initRecyclerView()
    {
        layoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);
        subTasksRecyclerViewAdapter = new SubTasksRecyclerViewAdapter(list, superTask, categoryId);
        recyclerView.setAdapter(subTasksRecyclerViewAdapter);
        new ItemTouchHelper(itemTouchHelperCallback).attachToRecyclerView(recyclerView);

        DividerItemDecoration dividerItemDecoration = new DividerItemDecoration(this, DividerItemDecoration.VERTICAL);
        dividerItemDecoration.setDrawable(getResources().getDrawable(R.drawable.divider_line, null));
        recyclerView.addItemDecoration(dividerItemDecoration);
    }

    private final TextView.OnEditorActionListener editorActionListener = (textView, i, keyEvent) -> {

        if (subTaskEditText.equals(textView))
        {
            onAddSubTaskClick();
        }
        else if (informationEditText.equals(textView))
        {
            onAddInformationClick();
        }

        return true;
    };

    private final View.OnFocusChangeListener onFocusChangeListener = (view, hasFocus) -> {
        if (!hasFocus)
        {
            onAddInformationClick();
        }
    };

    private void onAddSubTaskClick()
    {
        DatabaseReference databaseReference = firebaseHelper.getDatabaseReference()
                .child(categoryId).child(DatabaseNodes.TASKS).child(taskId).child(DatabaseNodes.SUB_TASKS_LIST);

        String text = subTaskEditText.getText().toString();

        if (text.trim().length() > 0)
        {
            String autoGeneratedId = databaseReference.push().getKey();

            if(autoGeneratedId != null)
            {
                list.add(new SubTask(text, autoGeneratedId));

                subTasksRecyclerViewAdapter.notifyItemInserted(list.size() - 1);

                subTaskEditText.getText().clear();

                databaseReference.child(autoGeneratedId).setValue(text);
            }
        }
    }

    private void onAddInformationClick()
    {
        DatabaseReference databaseReference = firebaseHelper.getDatabaseReference()
                .child(categoryId).child(DatabaseNodes.TASKS).child(taskId);

        String text = informationEditText.getText().toString();

        databaseReference.child(DatabaseNodes.TASK_INFORMATION).setValue(text);
    }

    ItemTouchHelper.SimpleCallback itemTouchHelperCallback = new ItemTouchHelper.SimpleCallback(0, ItemTouchHelper.LEFT) {
        @Override
        public boolean onMove(@NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder, @NonNull RecyclerView.ViewHolder target) {
            return false;
        }

        @Override
        public void onSwiped(@NonNull RecyclerView.ViewHolder viewHolder, int direction) {
            DatabaseReference databaseReference = firebaseHelper.getDatabaseReference()
                    .child(categoryId).child(DatabaseNodes.TASKS).child(taskId).child(DatabaseNodes.SUB_TASKS_LIST);

            String subTaskId = list.get(viewHolder.getBindingAdapterPosition()).getSubTaskId();

            list.remove(viewHolder.getBindingAdapterPosition());

            databaseReference.child(subTaskId).removeValue();

            subTasksRecyclerViewAdapter.notifyDataSetChanged();
        }

        @Override
        public void onChildDraw(@NonNull Canvas c, @NonNull RecyclerView recyclerView, @NonNull RecyclerView.ViewHolder viewHolder, float dX, float dY, int actionState, boolean isCurrentlyActive) {

            new RecyclerViewSwipeDecorator.Builder(c, recyclerView, viewHolder, dX, dY, actionState, isCurrentlyActive)
                    .addSwipeLeftBackgroundColor(ContextCompat.getColor(TaskItemActivity.this, R.color.colorRed))
                    .addSwipeLeftActionIcon(R.drawable.ic_delete_24dp)
                    .create()
                    .decorate();

            super.onChildDraw(c, recyclerView, viewHolder, dX, dY, actionState, isCurrentlyActive);
        }
    };

    @Override
    protected void onStop() {
        super.onStop();

        onAddInformationClick();
    }
}
